# =============================================================================
# Nyx Semantic Release Configuration
# =============================================================================

preset: "simple"
stateFile: ".nyx-state.json"

changelog:
  path: "CHANGELOG.md"

releaseTypes:
  publicationServices:
    - "github"
  items:
    mainline:
      gitCommit: "true"
      gitCommitMessage: "chore(release): {{version}} [skip ci]"

      gitTag: "true"
      gitTagForce: "true"
      gitTagMessage: "Release {{version}}"

      gitPush: "true"
      gitPushForce: "true"

      matchBranches: "^(main|master)$"
      publish: "true"
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"

services:
  github:
    type: "GITHUB"
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "cubiloc"
      REPOSITORY_OWNER: "Project-Carbonica"