# =============================================================================
# Nyx Semantic Release Configuration
# https://mooltiverse.github.io/nyx/docs/user/configuration-reference/
# =============================================================================

# Preset: simple - includes Conventional Commits support
preset: "simple"

# State file for CI/CD
stateFile: ".nyx-state.json"

# Changelog configuration
changelog:
  path: "CHANGELOG.md"

# Release types configuration
releaseTypes:
  publicationServices:
    - "github"
  items:
    mainline:
      gitCommit: "false"
      gitCommitMessage: "chore(release): {{version}}"
      gitTag: "true"
      gitTagForce: "true"
      gitTagMessage: "Release {{version}}"
      gitPush: "true"
      gitPushForce: "false"
      publish: "true"
      matchBranches: "^(main|master)$"
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"

# Git remote configuration for push operations
git:
  remotes:
    origin:
      user: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
      password: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"

# GitHub service configuration
services:
  github:
    type: "GITHUB"
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "cubiloc"
      REPOSITORY_OWNER: "Project-Carbonica"
