# =============================================================================
# Nyx Semantic Release Configuration
# =============================================================================

# Preset: simple - includes Conventional Commits support
preset: "simple"

# State file for CI/CD
stateFile: ".nyx-state.json"

# Changelog configuration
changelog:
  path: "CHANGELOG.md"
  # Opsiyonel: Changelog'a eklenecek şablonları buraya ekleyebilirsiniz.
  # sections: ...

# Release types configuration
releaseTypes:
  publicationServices:
    - "github"
  items:
    mainline:
      gitCommit: "true"
      gitCommitMessage: "chore(release): {{version}} [skip ci]"
      gitTag: "true"
      gitTagForce: "true"
      gitTagMessage: "Release {{version}}"
      gitPush: "true"
      publish: "true"
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"

# GitHub service configuration
services:
  github:
    type: "GITHUB"
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "cubiloc"
      REPOSITORY_OWNER: "Project-Carbonica"