// NOTE: This is a standalone example demonstrating Dagger 2 DI integration.
// Add to your project and update package as needed.
package example.di.dagger;

import dagger.Component;
import dagger.Module;
import dagger.Provides;
import example.ExampleMessages;
import net.cubizor.cubiloc.I18n;
import net.cubizor.cubiloc.inject.I18nBuilder;
import net.cubizor.cubiloc.locale.LocaleProvider;
import net.kyori.adventure.text.Component;

import javax.inject.Inject;
import javax.inject.Singleton;
import java.io.File;
import java.util.Locale;

/**
 * Example demonstrating Cubiloc integration with Dagger 2.
 * 
 * <p>Uses the new LocaleProvider-based API where I18n directly handles
 * player locale resolution - no I18nProvider needed!</p>
 */
public class DaggerExample {
    
    public static void main(String[] args) throws Exception {
        File dataFolder = new File("./test-data");
        
        // ========================================
        // Step 1: Build I18n with LocaleProvider
        // ========================================
        I18n i18n = I18nBuilder.create(Locale.forLanguageTag("tr-TR"))
            .localeProvider(new MockPlayerLocaleProvider())
            .register(ExampleMessages.class)
                .path("messages")
                .suffix(".yml")
                .unpack(true)
                .dataFolder(dataFolder)
                .done()
            .loadColorScheme("dark", "themes/dark.json")
            .loadColorScheme("light", "themes/light.json")
            .defaultScheme("dark")
            .build();
        
        // ========================================
        // Step 2: Create Dagger Component
        // ========================================
        // Note: DaggerAppComponent is generated by Dagger annotation processor
        // After running annotation processor:
        /*
        AppComponent component = DaggerAppComponent.builder()
            .appModule(new AppModule(i18n))
            .build();
        
        MessageService service = component.messageService();
        MockPlayer player = new MockPlayer("Deichor", "tr_TR");
        service.sendWelcome(player);
        */
        
        System.out.println("Dagger example - see comments for full usage");
    }
    
    // ========================================
    // Dagger Component & Module
    // ========================================
    
    @Singleton
    @Component(modules = {AppModule.class})
    public interface AppComponent {
        I18n i18n();
        MessageService messageService();
        
        @Component.Builder
        interface Builder {
            Builder appModule(AppModule module);
            AppComponent build();
        }
    }
    
    @Module
    public static class AppModule {
        private final I18n i18n;
        
        public AppModule(I18n i18n) {
            this.i18n = i18n;
        }
        
        @Provides @Singleton
        I18n provideI18n() {
            return i18n;
        }
    }
    
    // ========================================
    // Service with I18n Injection
    // ========================================
    
    @Singleton
    public static class MessageService {
        private final I18n i18n;
        
        @Inject
        public MessageService(I18n i18n) {
            this.i18n = i18n;
        }
        
        public void sendWelcome(MockPlayer player) {
            // NEW: i18n.config(player, Class) uses LocaleProvider automatically
            ExampleMessages msg = i18n.config(player, ExampleMessages.class);
            Component message = i18n.get(player, msg.welcome())
                .with("player", player.getName())
                .component();
            System.out.println("Welcome: " + message);
        }
        
        public void sendBalance(MockPlayer player, String amount, String currency) {
            ExampleMessages msg = i18n.config(player, ExampleMessages.class);
            String text = i18n.get(player, msg.balance())
                .with("amount", amount)
                .with("currency", currency)
                .asString();
            System.out.println("Balance: " + text);
        }
    }
    
    // ========================================
    // LocaleProvider & MockPlayer
    // ========================================
    
    public static class MockPlayerLocaleProvider implements LocaleProvider<MockPlayer> {
        @Override
        public boolean supports(Class<?> entityClass) {
            return MockPlayer.class.isAssignableFrom(entityClass);
        }
        
        @Override
        public Locale getLocale(MockPlayer entity) {
            return Locale.forLanguageTag(entity.getLocale().replace("_", "-"));
        }
    }
    
    public static class MockPlayer {
        private final String name;
        private final String locale;
        
        public MockPlayer(String name, String locale) {
            this.name = name;
            this.locale = locale;
        }
        
        public String getName() { return name; }
        public String getLocale() { return locale; }
    }
}
