// NOTE: This is a standalone example demonstrating Dagger 2 DI integration.
// Add to your project and update package as needed.
package example.di.dagger;

import dagger.Component;
import dagger.Module;
import dagger.Provides;
import example.ExampleMessages;
import net.cubizor.cubiloc.I18n;
import net.cubizor.cubiloc.inject.I18nBuilder;
import net.cubizor.cubiloc.inject.I18nProvider;
import net.cubizor.cubiloc.inject.dagger.CubilocDaggerModule;
import net.kyori.adventure.text.Component;

import javax.inject.Inject;
import javax.inject.Singleton;
import java.io.File;

/**
 * Example demonstrating Cubiloc integration with Dagger 2.
 * 
 * <p>This example shows:</p>
 * <ul>
 *   <li>How to set up I18n with I18nBuilder</li>
 *   <li>How to create a Dagger component with CubilocDaggerModule</li>
 *   <li>How to inject I18n and I18nProvider into services</li>
 * </ul>
 * 
 * <p>Note: This example won't compile directly - you need to run the Dagger
 * annotation processor to generate DaggerAppComponent.</p>
 */
public class DaggerExample {
    
    public static void main(String[] args) throws Exception {
        File dataFolder = new File("./test-data");
        
        // ========================================
        // Step 1: Build I18nProvider using I18nBuilder
        // ========================================
        I18nProvider provider = I18nBuilder.create("tr_TR")
            .register(ExampleMessages.class)
                .path("messages")
                .suffix(".yml")
                .unpack(true)
                .dataFolder(dataFolder)
                .done()
            .loadColorScheme("dark", "themes/dark.json")
            .loadColorScheme("light", "themes/light.json")
            .defaultScheme("dark")
            .buildProvider();
        
        // ========================================
        // Step 2: Create Dagger Component
        // ========================================
        // Note: DaggerAppComponent is generated by Dagger annotation processor
        // After running the annotation processor, uncomment these lines:
        /*
        AppComponent component = DaggerAppComponent.builder()
            .cubilocDaggerModule(new CubilocDaggerModule(provider))
            .build();
        
        // Get services with injected I18n
        MessageService messageService = component.messageService();
        
        // Use the service
        MockPlayer player = new MockPlayer("Deichor", "tr_TR");
        
        System.out.println("=== Dagger 2 DI Example ===");
        messageService.sendWelcome(player);
        messageService.sendBalance(player, "5000", "TL");
        */
        
        System.out.println("Dagger example - see comments for usage after annotation processing");
    }
    
    // ========================================
    // Dagger Component Definition
    // ========================================
    
    /**
     * Main Dagger component that provides all dependencies.
     * Dagger will generate DaggerAppComponent implementation.
     */
    @Singleton
    @Component(modules = {CubilocDaggerModule.class})
    public interface AppComponent {
        
        // Expose I18n dependencies
        I18n i18n();
        I18nProvider i18nProvider();
        
        // Expose services
        MessageService messageService();
        
        // Factory for building component
        @Component.Builder
        interface Builder {
            Builder cubilocDaggerModule(CubilocDaggerModule module);
            AppComponent build();
        }
    }
    
    // ========================================
    // Services with Dependency Injection
    // ========================================
    
    /**
     * Example service that receives I18nProvider via constructor injection.
     */
    @Singleton
    public static class MessageService {
        
        private final I18nProvider i18nProvider;
        
        @Inject
        public MessageService(I18nProvider i18nProvider) {
            this.i18nProvider = i18nProvider;
        }
        
        public void sendWelcome(MockPlayer player) {
            ExampleMessages msg = i18nProvider.config(player, ExampleMessages.class);
            Component message = i18nProvider.i18n().get(player, msg.welcome())
                .with("player", player.getName())
                .component();
            
            System.out.println("Welcome: " + message);
        }
        
        public void sendBalance(MockPlayer player, String amount, String currency) {
            ExampleMessages msg = i18nProvider.config(player, ExampleMessages.class);
            String text = i18nProvider.i18n().get(player, msg.balance())
                .with("amount", amount)
                .with("currency", currency)
                .asString();
            
            System.out.println("Balance: " + text);
        }
        
        public void sendError(MockPlayer player, String item) {
            ExampleMessages msg = i18nProvider.config(player, ExampleMessages.class);
            Component error = i18nProvider.i18n().get(player, msg.errors().notFound())
                .with("item", item)
                .component();
            
            System.out.println("Error: " + error);
        }
    }
    
    /**
     * Another service example showing direct I18n injection.
     */
    @Singleton
    public static class AnotherService {
        
        private final I18n i18n;
        
        @Inject
        public AnotherService(I18n i18n) {
            this.i18n = i18n;
        }
        
        public void showServerName() {
            ExampleMessages msg = i18n.config(ExampleMessages.class);
            System.out.println("Server: " + i18n.get(msg.serverName()).asString());
        }
    }
    
    /**
     * Mock player for testing.
     */
    public static class MockPlayer {
        private final String name;
        private final String locale;
        
        public MockPlayer(String name, String locale) {
            this.name = name;
            this.locale = locale;
        }
        
        public String getName() {
            return name;
        }
        
        public String getLocale() {
            return locale;
        }
    }
}
